/// <reference types = "cypress" />
import * as data from "../support/variables.js";
//import * as locators from "../support/locators.js";

describe('Validate Shopping Cart', () => {

    it('Remove all itens from shopping cart', () => {
        cy.intercept({ resourceType: /xhr|fetch/ }, { log: false })
        cy.viewport(1349, 606)
        cy.clearAllSessionStorage({log: true})
        cy.visit('https://www.saucedemo.com/', {failOnStatusCode: false})
        cy.get('[data-test="username"]').type(data.user.username)
        cy.get('[data-test="password"]').type(data.user.password)
        cy.get('[data-test="login-button"]').click()
        cy.contains(data.item1.name)
        cy.get(data.item1.buttonId).contains(data.item1.price)
        cy.contains('Add to cart').click()
        cy.contains(data.item2.name)
        cy.get(data.item2.buttonId).contains(data.item2.price)
        cy.contains('Add to cart').click()
        cy.contains(data.item3.name)
        cy.get(data.item3.buttonId).contains(data.item3.price)
        cy.contains('Add to cart').click()
        cy.contains(data.item4.name)
        cy.get(data.item4.buttonId).contains(data.item4.price)
        cy.contains('Add to cart').click()
        cy.contains(data.item5.name)
        cy.get(data.item5.buttonId).contains(data.item5.price)
        cy.contains('Add to cart').click()
        cy.get(data.item6.buttonId).contains(data.item6.price)
        cy.contains(data.item6.name)
        cy.contains('Add to cart').click()
        cy.get('.shopping_cart_badge').contains('6')
        cy.get('.shopping_cart_link').click()
        cy.get(data.item1.removeButtonId).click()
        cy.get('.cart_list').should('not.include.text', data.item1.name)
        cy.get(data.item2.removeButtonId).click()
        cy.get('.cart_list').should('not.include.text', data.item2.name)
        cy.get(data.item3.removeButtonId).click()
        cy.get('.cart_list').should('not.include.text', data.item3.name)
        cy.get(data.item4.removeButtonId).click()
        cy.get('.cart_list').should('not.include.text', data.item4.name)
        cy.get(data.item5.removeButtonId).click()
        cy.get('.cart_list').should('not.include.text', data.item5.name)
        cy.get(data.item6.removeButtonId).click()
        cy.get('.cart_list').should('not.include.text', data.item6.name)
        
    });

    it('Check Sauce Labs Backpack Product Details', () => {
        cy.intercept({ resourceType: /xhr|fetch/ }, { log: false })
        cy.viewport(1349, 606)
        cy.clearAllSessionStorage({log: true})
        cy.visit('https://www.saucedemo.com/', {failOnStatusCode: false})
        cy.get('[data-test="username"]').type(data.user.username)
        cy.get('[data-test="password"]').type(data.user.password)
        cy.get('[data-test="login-button"]').click()
        cy.contains(data.item1.name).click()
        cy.get('.inventory_details_name').contains(data.item1.name)
        cy.get('.inventory_details_desc').contains(data.item1.description)
        cy.get('.inventory_details_price').contains(data.item1.price)
    });

    it('Check Sauce Labs Bike Light Product Details', () => {
        cy.intercept({ resourceType: /xhr|fetch/ }, { log: false })
        cy.viewport(1349, 606)
        cy.clearAllSessionStorage({log: true})
        cy.visit('https://www.saucedemo.com/', {failOnStatusCode: false})
        cy.get('[data-test="username"]').type(data.user.username)
        cy.get('[data-test="password"]').type(data.user.password)
        cy.get('[data-test="login-button"]').click()
        cy.contains(data.item2.name).click()
        cy.get('.inventory_details_name').contains(data.item2.name)
        cy.get('.inventory_details_desc').contains(data.item2.description)
        cy.get('.inventory_details_price').contains(data.item2.price)
    });

    it('Check Sauce Labs Bolt T-Shirt Product Details', () => {
        cy.intercept({ resourceType: /xhr|fetch/ }, { log: false })
        cy.viewport(1349, 606)
        cy.clearAllSessionStorage({log: true})
        cy.visit('https://www.saucedemo.com/', {failOnStatusCode: false})
        cy.get('[data-test="username"]').type(data.user.username)
        cy.get('[data-test="password"]').type(data.user.password)
        cy.get('[data-test="login-button"]').click()
        cy.contains(data.item3.name).click()
        cy.get('.inventory_details_name').contains(data.item3.name)
        cy.get('.inventory_details_desc').contains(data.item3.description)
        cy.get('.inventory_details_price').contains(data.item3.price)
    });

    it('Check Sauce Labs Fleece Jacket Product Details', () => {
        cy.intercept({ resourceType: /xhr|fetch/ }, { log: false })
        cy.viewport(1349, 606)
        cy.clearAllSessionStorage({log: true})
        cy.visit('https://www.saucedemo.com/', {failOnStatusCode: false})
        cy.get('[data-test="username"]').type(data.user.username)
        cy.get('[data-test="password"]').type(data.user.password)
        cy.get('[data-test="login-button"]').click()
        cy.contains(data.item4.name).click()
        cy.get('.inventory_details_name').contains(data.item4.name)
        cy.get('.inventory_details_desc').contains(data.item4.description)
        cy.get('.inventory_details_price').contains(data.item4.price)
    });
    
    it('Check Sauce Labs Onesie Product Details', () => {
        cy.intercept({ resourceType: /xhr|fetch/ }, { log: false })
        cy.viewport(1349, 606)
        cy.clearAllSessionStorage({log: true})
        cy.visit('https://www.saucedemo.com/', {failOnStatusCode: false})
        cy.get('[data-test="username"]').type(data.user.username)
        cy.get('[data-test="password"]').type(data.user.password)
        cy.get('[data-test="login-button"]').click()
        cy.contains(data.item5.name).click()
        cy.get('.inventory_details_name').contains(data.item5.name)
        cy.get('.inventory_details_desc').contains(data.item5.description)
        cy.get('.inventory_details_price').contains(data.item5.price)
    });

    it("Check Test.allTheThings() T-Shirt (Red) Product Details", () => {
        cy.intercept({ resourceType: /xhr|fetch/ }, { log: false })
        cy.viewport(1349, 606)
        cy.clearAllSessionStorage({log: true})
        cy.visit('https://www.saucedemo.com/', {failOnStatusCode: false})
        cy.get('[data-test="username"]').type(data.user.username)
        cy.get('[data-test="password"]').type(data.user.password)
        cy.get('[data-test="login-button"]').click()
        cy.contains(data.item6.name).click()
        cy.get('.inventory_details_name').contains(data.item6.name)
        cy.get('.inventory_details_desc').contains(data.item6.description)
        cy.get('.inventory_details_price').contains(data.item6.price)
    });

    it('Add all items to shopping cart', () => {
        cy.intercept({ resourceType: /xhr|fetch/ }, { log: false })
        cy.viewport(1349, 606)
        cy.clearAllSessionStorage({log: true})
        cy.visit('https://www.saucedemo.com/', {failOnStatusCode: false})
        cy.get('[data-test="username"]').type(data.user.username)
        cy.get('[data-test="password"]').type(data.user.password)
        cy.get('[data-test="login-button"]').click()
        cy.contains('Sauce Labs Backpack')
        cy.get(data.item1.buttonId).contains(data.item1.price)
        cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').click()
        cy.contains(data.item2.name)
        cy.get(data.item2.buttonId).contains(data.item2.price)
        cy.get('[data-test="add-to-cart-sauce-labs-bike-light"]').click()
        cy.contains(data.item3.name)
        cy.get(data.item3.buttonId).contains(data.item3.price)
        cy.get('[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]').click()
        cy.contains(data.item4.name)
        cy.get(data.item4.buttonId).contains(data.item4.price)
        cy.get('[data-test="add-to-cart-sauce-labs-fleece-jacket"]').click()
        cy.contains(data.item5.name)
        cy.get(data.item5.buttonId).contains(data.item5.price)
        cy.get('[data-test="add-to-cart-sauce-labs-onesie"]').click()
        cy.get(data.item6.buttonId).contains(data.item6.price)
        cy.contains(data.item6.name)
        cy.get('[data-test="add-to-cart-test.allthethings()-t-shirt-(red)"]').click()
        cy.get('.shopping_cart_badge').contains('6')
    });

    it('Add all items to shopping cart and buy it', () => {
        cy.intercept({ resourceType: /xhr|fetch/ }, { log: false })
        cy.viewport(1349, 606)
        cy.clearAllSessionStorage({log: true})
        cy.visit('https://www.saucedemo.com/', {failOnStatusCode: false})
        cy.get('[data-test="username"]').type(data.user.username)
        cy.get('[data-test="password"]').type(data.user.password)
        cy.get('[data-test="login-button"]').click()
        cy.contains('Sauce Labs Backpack')
        cy.get(data.item1.buttonId).contains(data.item1.price)
        cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').click()
        cy.contains(data.item2.name)
        cy.get(data.item2.buttonId).contains(data.item2.price)
        cy.get('[data-test="add-to-cart-sauce-labs-bike-light"]').click()
        cy.contains(data.item3.name)
        cy.get(data.item3.buttonId).contains(data.item3.price)
        cy.get('[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]').click()
        cy.contains(data.item4.name)
        cy.get(data.item4.buttonId).contains(data.item4.price)
        cy.get('[data-test="add-to-cart-sauce-labs-fleece-jacket"]').click()
        cy.contains(data.item5.name)
        cy.get(data.item5.buttonId).contains(data.item5.price)
        cy.get('[data-test="add-to-cart-sauce-labs-onesie"]').click()
        cy.get(data.item6.buttonId).contains(data.item6.price)
        cy.contains(data.item6.name)
        cy.get('[data-test="add-to-cart-test.allthethings()-t-shirt-(red)"]').click()
        cy.get('.shopping_cart_badge').contains('6')
        cy.get('.shopping_cart_link').click()
        cy.get(data.item1.cartId).contains(data.item1.price)
        cy.get(data.item2.cartId).contains(data.item2.price)
        cy.get(data.item3.cartId).contains(data.item3.price)
        cy.get(data.item4.cartId).contains(data.item4.price)
        cy.get(data.item5.cartId).contains(data.item5.price)
        cy.get(data.item6.cartId).contains(data.item6.price)
        cy.get('[data-test="checkout"]').click()
        cy.get('[data-test="firstName"]').type(data.user.firstname)
        cy.get('[data-test="lastName"]').type(data.user.lastname)
        cy.get('[data-test="postalCode"]').type(data.user.postalcode)
        cy.get('[data-test="continue"]').click()
        cy.get(data.item1.cartId).contains(data.item1.price)
        cy.get(data.item2.cartId).contains(data.item2.price)
        cy.get(data.item3.cartId).contains(data.item3.price)
        cy.get(data.item4.cartId).contains(data.item4.price)
        cy.get(data.item5.cartId).contains(data.item5.price)
        cy.get(data.item6.cartId).contains(data.item6.price)
        cy.get('.summary_total_label').contains('140.34')
        cy.get('[data-test="finish"]').click()
        cy.get('.complete-header').contains('Thank you for your order!')
        cy.get('.complete-text').contains('Your order has been dispatched, and will arrive just as fast as the pony can get there!')
        cy.get('[data-test="back-to-products"]').click()
    });
});